<a href="https://colab.research.google.com/github/stacykeago/fundamentals-of-data-analytics/blob/main/FDA_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Define the question:

# Metric of success
The likelihood of a claim being rejected could be evaluated based on several key performance indicators (KPIs) commonly used in machine learning classification tasks.
1. Accuracy
2. Precision
3. Recall (Sensitivity)
4. F1 Score
5. Area Under the ROC Curve (AUC-ROC)
6. Confusion Matrix

Resources that support this analysis
1. [Business Insights & Recommendations](https://docs.google.com/document/d/1q9gwblcG5X_Cm1P03Y4Zzbr2ue-CVVN8ecXmyi_yRAM/edit?usp=sharing)
2.

# Data used:
1. [Path to data ](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv)

# a. EXPLORATTORY DATA ANALYSIS (EDA)

## 1.0 Import the libraries to be used

In [4]:
import numpy as np # for linear algebra
import pandas as pd # for data processing
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
from sklearn.preprocessing import LabelEncoder # the libraries for label encoding

## 2.0 Upload Dataset

In [2]:
# My dataset is saved in my Google Drive.
# Mount Google drive to colab to access dataset

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
pd.set_option('display.max_columns', None) # ensures all columns are displayed
auto = pd.read_csv('/content/drive/MyDrive/BSBI/auto.csv', header=None)
auto.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

### Column names

In [22]:
auto.columns

Index(['3', '?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd',
       'front', '88.6', '168.8', '64.1', '48.8', '2548', 'dohc', 'four', '130',
       'mpfi', '3.47', '2.68', '9.0', '111', '5000', '21', '27', '13495'],
      dtype='object')

### 2.1 Number of rows and columns

In [9]:
# Print number of rows and columns
print(f"Rows: {auto.shape[0]}, Columns: {auto.shape[1]}")

Rows: 204, Columns: 26

### 2.2 Data types in each column

In [13]:
auto.dtypes

3                int64
?               object
alfa-romero     object
gas             object
std             object
two             object
convertible     object
rwd             object
front           object
88.6           float64
168.8          float64
64.1           float64
48.8           float64
2548             int64
dohc            object
four            object
130              int64
mpfi            object
3.47            object
2.68            object
9.0            float64
111             object
5000            object
21               int64
27               int64
13495           object
dtype: object

### 2.3 Basic info of the data

In [14]:
# Display basic information about the columns
print(auto.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            204 non-null    int64
 1   ?            204 non-null    object
 2   alfa-romero  204 non-null    object
 3   gas          204 non-null    object
 4   std          204 non-null    object
 5   two          204 non-null    object
 6   convertible  204 non-null    object
 7   rwd          204 non-null    object
 8   front        204 non-null    object
 9   88.6         204 non-null    float64
 10  168.8        204 non-null    float64
 11  64.1         204 non-null    float64
 12  48.8         204 non-null    float64
 13  2548         204 non-null    int64
 14  dohc         204 non-null    object
 15  four         204 non-null    object
 16  130          204 non-null    int64
 17  mpfi         204 non-null    object
 18  3.47         204 non-null    object
 19  2.68         204 non-null    object
 20  9.0          204 non-null    float64
 21  111          204 non-null    object
 22  5000         204 non-null    object
 23  21           204 non-null    int64
 24  27           204 non-null    int64
 25  13495        204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB
None

### 2.4 Null values

In [15]:
# To check for Null values to ensures the integrity of your dataset.
auto.isnull().sum()

3              0
?              0
alfa-romero    0
gas            0
std            0
two            0
convertible    0
rwd            0
front          0
88.6           0
168.8          0
64.1           0
48.8           0
2548           0
dohc           0
four           0
130            0
mpfi           0
3.47           0
2.68           0
9.0            0
111            0
5000           0
21             0
27             0
13495          0
dtype: int64

No null values in the auto dataset

### 2.5 Duplicates

In [16]:
#check for duplicates : Duplicates are noise to the data
np.sum(auto.duplicated())

np.int64(0)

### 2.6 Unique features in the data

In [18]:
# count of unique values for each column in the DataFrame.
auto.nunique()

3                6
?               52
alfa-romero     22
gas              2
std              2
two              3
convertible      5
rwd              3
front            2
88.6            53
168.8           75
64.1            44
48.8            49
2548           171
dohc             7
four             7
130             44
mpfi             8
3.47            39
2.68            37
9.0             32
111             60
5000            24
21              29
27              30
13495          186
dtype: int64

### 2.7 Outliers

# b. Univariate Analysis

# c. Bivariate Analysis

# d. Multivariate Analysis

## Feature selection
• What features seem most related to price?

# HYPOTHESIS TESTING
1. Does higher horsepower always mean higher price?